/**
 * @file
 * @brief Reads matrix from ascii-formatted files generated by Matlab's 'save' function.
 */

#include "readMatrix.h"
#include <fstream>

/**
 * @defgroup readMatrix readMatrix
 * @ingroup readMatrix
 * @brief Reads matrix from ascii-formatted files generated by Matlab's 'save' function.
 * @param filename Name of text file to be read
 * @returns Eigen array with matrix from text file
 */
Mat readMatrix(std::string filename, int nr, int nc) {
    std::ifstream afile;
    afile.open(filename.c_str());
    Mat result(nr, nc);
    uint32 row = 0;
    uint32 col = 0;
    real number;
    while(afile >> number){
        result(row, col) = number;
        if(col == 255){
            row += 1;
            col = 0;
        } else {
            ++col;
        }
    }
    return result;
}