/**
 * @file
 * @brief Reads seed coordinates from ascii-formatted files generated by
 * Matlab's 'save' function.
 *
 * @date Created 25/07/18
 * @author Jack Scantlebury
 */
#include "readSeeds.h"
#include <string>
#include <fstream>

/**
 * @defgroup readSeeds readSeeds
 * @ingroup readSeeds
 *
 * @brief Reads seed coordinates from ascii-formatted files generated by
 * Matlab's 'save' function.
 *
 * @param filename Name of text file to be read
 * @returns std::vector containing two std::vector<double>: the x and y
 * coordinates of the seeds
 */
std::vector<RealVec> readSeeds(std::string filename) {

    // Open stream
    std::ifstream afile;
    afile.open(filename.c_str());

    // Initialise coordinate lists
    RealVec Sx;
    RealVec Sy;
    uint32 x = 0;
    real number;

    // Populate Sx and Sy
    while(afile >> number){
        if(x % 2 == 0){
            Sx.push_back(number);
        } else {
            Sy.push_back(number);
        }
        x += 1;
    }

    // Put Sx and Sy into n x 2 result vector
    std::vector<RealVec> result;
    result.push_back(Sx);
    result.push_back(Sy);
    return result;
}