/**
 * @file
 * @brief Reads seed coordinates from ascii-formatted files generated by Matlab's 'save' function.
 */
#include "readSeeds.h"
#include <string>
#include <fstream>

/**
 * @defgroup readSeeds readSeeds
 * @ingroup readSeeds
 * @brief Reads seed coordinates from ascii-formatted files generated by Matlab's 'save' function.
 * @param filename Name of text file to be read
 * @returns Vector containing two std::vector<double>: the x and y coordinates of the seeds
 */
std::vector<RealVec> readSeeds(std::string filename) {
    std::ifstream afile;
    afile.open(filename.c_str());
    RealVec Sx;
    RealVec Sy;
    uint32 x = 0;
    real number;
    while(afile >> number){
        if(x % 2 == 0){
            Sx.push_back(number);
        } else {
            Sy.push_back(number);
        }
        x += 1;
    }
    std::vector<RealVec> result;
    result.push_back(Sx);
    result.push_back(Sy);
    return result;
}